version: '3'

services:
  web:
    container_name: bookshop_web
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    network_mode: "host"
    restart: always
